# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\python\practice\helloworld\.ui\extrafunction.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_extrafunction(object):
    def setupUi(self, extrafunction):
        extrafunction.setObjectName("extrafunction")
        extrafunction.resize(500, 500)
        extrafunction.setStyleSheet("QPushButton:hover { color: red }\n"
"QPushButton {   \n"
"    width:50px;\n"
"    height:20px;\n"
"    font: 75 9pt \"Bahnschrift Condensed\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(extrafunction)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet("QPushButton:hover { color: red }")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setStyleSheet("QPushButton { \n"
"    color: red ;\n"
"    font-size:15px;\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout.addWidget(self.plainTextEdit)
        extrafunction.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(extrafunction)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        extrafunction.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(extrafunction)
        self.statusbar.setObjectName("statusbar")
        extrafunction.setStatusBar(self.statusbar)

        self.retranslateUi(extrafunction)
        QtCore.QMetaObject.connectSlotsByName(extrafunction)

    def retranslateUi(self, extrafunction):
        _translate = QtCore.QCoreApplication.translate
        extrafunction.setWindowTitle(_translate("extrafunction", "Eetrafunction"))
        self.pushButton.setText(_translate("extrafunction", "鼠标区"))
        self.pushButton_2.setText(_translate("extrafunction", "壁纸区"))
        self.pushButton_3.setText(_translate("extrafunction", "ai绘画区"))
        self.pushButton_4.setText(_translate("extrafunction", "设置区"))
