# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\python\practice\helloworld\.ui\mouse.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_mouse(object):
    def setupUi(self, mouse):
        mouse.setObjectName("mouse")
        mouse.resize(513, 500)
        mouse.setStyleSheet("QPushButton:hover { color: red }\n"
"QPushButton {   \n"
"    width:50px;\n"
"    height:20px;\n"
"    font: 75 9pt \"Bahnschrift Condensed\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(mouse)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.buttonGroup = QtWidgets.QButtonGroup(mouse)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pushButton_2)
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.buttonGroup.addButton(self.pushButton_3)
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.buttonGroup.addButton(self.pushButton_4)
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.buttonGroup.addButton(self.pushButton)
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        mouse.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mouse)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 513, 22))
        self.menubar.setObjectName("menubar")
        mouse.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mouse)
        self.statusbar.setObjectName("statusbar")
        mouse.setStatusBar(self.statusbar)

        self.retranslateUi(mouse)
        QtCore.QMetaObject.connectSlotsByName(mouse)

    def retranslateUi(self, mouse):
        _translate = QtCore.QCoreApplication.translate
        mouse.setWindowTitle(_translate("mouse", "Mouse"))
        self.pushButton_2.setText(_translate("mouse", "壁纸区"))
        self.pushButton_3.setText(_translate("mouse", "ai绘画区"))
        self.pushButton_4.setText(_translate("mouse", "额外功能区"))
        self.pushButton.setText(_translate("mouse", "设置区"))
        self.pushButton_5.setText(_translate("mouse", "选择本地文件"))
        self.pushButton_6.setText(_translate("mouse", "下载并应用资源"))
if __name__ == "__main__":
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QMainWindow()
    ui = Ui_mouse()
    # 我这边是默认的Ui_MainWindow，要是你们自己有修改，这边要相应修改
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())